apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://github.com/pkalbande/jenkins-setup.git
      targetRevision: main
      chart: jenkins
      path: jenkins-chart/jenkins
      helm:
        valueFiles:
          - values-local.yaml
    - repoURL: https://github.com/pkalbande/jenkins-setup.git
      targetRevision: main
      ref: values